spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/saller?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 10.3.25.1
    username: guest
    password: guest
server:
  port: 8082
  context-path: /saller
rpc:
  server:
    url: http://localhost:8081/manager/
  client:
    basepackage: com.yxdtyut.rpc
