spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
  rabbitmq:
    host: 10.3.25.1
    username: guest
    password: guest
server:
  port: 8081
  context-path: /manager
swagger:
  groupName: manager
  base-package: com.yxdtyut.manager.controller
