spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true
server:
  port: 8081
  context-path: /manager